name: json_analyze
description: "A Flutter project to switch between json and data model."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: 4.9.0
  freezed_annotation: 2.4.4
  analyzer_query:
    path: ./plugin/analyzer_query


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0

flutter:
  uses-material-design: true
